version: '3'
services:
  grantsearch:
    image: hirotoyo/grantsearch:latest
    ports:
      - "8501:8501"
    volumes:
      - ./data/results:/app/google-adk/results
      - ./data/logs:/app/google-adk/logs
      - ./data/knowledge:/app/google-adk/knowledge
      - ./data/.env:/app/google-adk/.env 