version: '3'

services:
  grantsearch:
    image: hirotoyo/grantsearch:latest
    ports:
      - "8501:8501"
    volumes:
      # /workspace パス用のマウント
      - ./data/results:/workspace/google-adk/results
      - ./data/logs:/workspace/google-adk/logs
      - ./data/knowledge:/workspace/google-adk/knowledge
      - ./data/.env:/workspace/google-adk/.env